//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeATrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranks
    {

        public int WebsiteId { get; set; }
        public int AttrId { get; set; }
        public double Rank { get; set; }
    
        public virtual Websites Websites { get; set; }
        public virtual Attractions Attractions { get; set; }
    }
}
